#define TAPPING_TERM 175
#define COMBO_TERM 250

#define LSPO_KEYS KC_LSFT, KC_LSFT, KC_LBRC
#define RSPC_KEYS KC_RSFT, KC_RSFT, KC_RBRC
#define LCPO_KEYS KC_LCTL, KC_TRNS, KC_LBRC
#define RCPC_KEYS KC_RCTL, KC_TRNS, KC_RBRC
#define LAPO_KEYS KC_LALT, KC_TRNS, KC_LBRC
#define RAPC_KEYS KC_RALT, KC_TRNS, KC_RBRC

#define COMBO_COUNT 6